language: node_js
node_js:
  - 'iojs'

install:
  - 'npm install'
  - 'npm install -g bower'
  - 'bower install'

script: 'gulp assets test'

env:
  - 'TC_COVERAGE=true'

after_success:
  - 'npm install -g codeclimate-test-reporter'
  - 'codeclimate < coverage/lcov.info'
